<?php


namespace app\models;

use yii\db\ActiveRecord;
use backend\controllers\CategoryController;
use yii\helpers\Url;
use yii\web\Linkable;
use yii\web\Link;


class Product extends ActiveRecord
{

//    public function getLinks()
//    {
//        return [
////            'alinur' => Url::to(['product', $this->id], true)
//            Link::REL_SELF => Url::to(['', '/' => $this->id], true)
//        ];
//    }

//    public function rules()
//    {
//        return [
//          [['id', 'name'], 'required']
//        ];
//    }

    public function fields()
    {

        return parent::fields(); // TODO: Change the autogenerated stub
    }


}