<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\web\IdentityInterface;
use backend\controllers\Traits\TraitIdentityInterface;


class User extends ActiveRecord
{

    public function rules()
    {
        return [
            [['name', 'email', 'password', 'role'], 'required'],
            ['email', 'email']

        ];
    }



//    public function behaviors()
//    {
//        $behaviors = parent::behaviors();
//        $behaviors['authenticator'] = [
//            'class' => CompositeAuth::className(),
//            'authMethods' => [
//                HttpBasicAuth::className(),
//                HttpBearerAuth::className(),
//                QueryParamAuth::className(),
//            ],
//        ];
//        return $behaviors;
//    }
//
//    public function fields()
//    {
//
//        return parent::fields(); // TODO: Change the autogenerated stub
//    }

}